---
- name: Add or update registry path MyCompany, with dword entry 'hello', and containing 1337 as the decimal value
  ansible.windows.win_regedit:
    path: HKCU:\Software\MyCompany
    name: hello
    data: 1337
    type: dword

- name: write to file
  ansible.windows.win_shell: |
    $result = get-service spooler | convertTO-json -depth 2
    $result | out-file c:\temp\ah.json
    $result